### ISSUE TITLE
Error building the with the hugo book theme

### ISSUE THREAD

**Issue by vuvgaG** [jojomi/docker-hugo#112]
Its just a plane site with the hugo-book theme

I'm getting the error:

![image](https://user-images.githubusercontent.com/75189112/124381950-f3f7d580-dcbc-11eb-95d6-ffbfd4670fb4.png)

**Comment by jojomi** [comment]
did you solve the problem yourself? I guess it probably was Hugo related?

**Comment by vuvgaG** [comment]
Yeah I missed the hugo theme option. I thought it would have been picked up by the container. My bad sorry. 

Thanks for your time and work!
