### ISSUE TITLE
No need to have the binary in the repo

### ISSUE THREAD

**Issue by marians** [jojomi/docker-hugo#2]
Have you tried this?

```
RUN apk add --update wget ca-certificates && \
  wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_linux_amd64.tar.gz && \
  tar xzf hugo_0.14_linux_amd64.tar.gz && \
  rm -r hugo_0.14_linux_amd64.tar.gz && \
  mv hugo_0.14_linux_amd64/hugo_0.14_linux_amd64 /usr/bin/hugo && \
  rm -r hugo_0.14_linux_amd64 && \
  apk del wget ca-certificates && \
  rm /var/cache/apk/*
```

**Comment by jojomi** [comment]
Actually that is a good idea. When I built this image some months ago and was still learning about Docker and images I liked to have the binary locally available. But that probably is not an issue here, this image is not going to be rebuilt a lot.

Thank your for taking the time to open this issue.

May I ask how you got to know about this image and if you used it successfully? Would it meet your needs?

**Comment by marians** [comment]
I was just googling for `hugo docker` to see if there is any very popular image before I would make an effort to create one fitting our specific need. Also to see if somebody is doing it really well. Basically I need just the executable in an Alpine image, so yours is close to what I'll build.

**Comment by jojomi** [comment]
Your lines worked fine for me. I extracted the version to an environment variable, so we don't have it explicitly set all over the `Dockerfile` and pushed the updated version. I also removed the 0.13 branch. If anyone really needs old code, he or she can just fork the repo and change that one environment variable.

Thank you again for your contribution!
