### ISSUE TITLE
Hugo server cannot be accessed when using Docker Toolbox

### ISSUE THREAD

**Issue by brightredchilli** [jojomi/docker-hugo#24]
...because, docker only listens to requests from localhost by default. In the docker toolbox setup, docker host is on a virtual machine.

Changing this in this setup would require a bind variable to be introduced in run.sh, which I didn't do. I ended up just using this, modifying the hugo command like so:
```
hugo server --bind="0.0.0.0"
```

Another small note: inotify doesnt work on Virtualbox on mac([issue](https://blog.codecentric.de/en/2017/08/fix-webpack-watch-virtualbox/)), hugo server doesnt watch changes when run inside a container. Sad. I wrote a small script that fixes it for [me](https://gist.github.com/brightredchilli/f912d87977399ccdace8041fd2812db4)

Hopefully all of this helps someone else out.

**Comment by jojomi** [comment]
Thank you for taking your time to share your experience, bugs and fixes!

Isn't your first point fixed in this line already? https://github.com/jojomi/docker-hugo/blob/master/run.sh#L19

**Comment by brightredchilli** [comment]
oh so true!! im not sure why it didn't work for me. i think i might have got lost in trying to get auto-reload to work that i fudged something. My bad!

**Comment by jojomi** [comment]
No problem! I think I will close this ticket, but we still have a source of information for those who might face the same issue.
