### ISSUE TITLE
Consider Renovate

### ISSUE THREAD

**Issue by hbetts** [jojomi/docker-hugo#30]
Please consider adopting Renovate, which supports automatically updating a project's `Dockerfile` with the digest value for the Docker image specified in the `FROM` instruction - https://renovateapp.com/docs/language-support/docker

This helps to insure build reproducibility as anytime this project is built, it will use the exact version of the Alpine image.

**Comment by jojomi** [comment]
Interesting idea, thanks for sharing it. I enabled it for this repository, let's see if it works for my workflow (update frequency in `alpine`?).
