### ISSUE TITLE
DockerHub 0.36.1 build failed

### ISSUE THREAD

**Issue by tehuel** [jojomi/docker-hugo#34]
I can't see why it failed, so i have no more info to provide you.

Anyways im creating the issue to let you know about the error: https://hub.docker.com/r/jojomi/hugo/builds/bnzpvfpwhaqsnzlbhd3qwre/

**Comment by jojomi** [comment]
Thank you for reporting this! It seems Docker Hub had some internal problems while building the last tags I submitted. I reissued them manually and after a while it worked. So you can use the new tags now.
