### ISSUE TITLE
/run.sh: line 30: /usr/local/sbin/hugo: not found  in Version 0.43

### ISSUE THREAD

**Issue by svenlange** [jojomi/docker-hugo#46]
When I run `docker run jojomi/hugo:0.43` on my terminal the following error appears:

```
sven@computer:~/$ docker run jojomi/hugo:0.43
HUGO_WATCH: false
HUGO_REFRESH_TIME: -1
HUGO_THEME:
HUGO_BASEURL
ARGS
Hugo path: /usr/local/sbin/hugo
Building one time...
/run.sh: line 30: /usr/local/sbin/hugo: not found
```

**Comment by jojomi** [comment]
I will have a look, currently thinking if the image should just ship the basic binary for now and wait how the SCSS features develop?

**Comment by jojomi** [comment]
https://github.com/gohugoio/hugo/issues/4923#issuecomment-403732426

**Comment by jojomi** [comment]
@LorenzCK Thank you for your input on the issue.

@svenlange can you check again if it works now? I have reverted to the basic hugo version for now and pushed the `0.43` and `latest` tags. Imho we should strive for a (additional?) build of the extended version once the documentation is on par with the features.

**Comment by svenlange** [comment]
It is working now. Thanks!

**Comment by LorenzCK** [comment]
Works now, thank you for your time @jojomi. 👍

FYI: you may want to take a look to [the same issue for the klakegg/hugo image](https://github.com/klakegg/docker-hugo/issues/1), where libraries are now imported from an Ubuntu image in a multistage build in order to make Hugo 0.43 extended work.

**Comment by jojomi** [comment]
Thank you both for testing and especially @LorenzCK for the link to the repo that reserves a lot more stars for the work done there!

**Comment by jojomi** [comment]
At least I got the 0.44 build done today already ;)
