### ISSUE TITLE
Docker image for v0.47 not found

### ISSUE THREAD

**Issue by superbrothers** [jojomi/docker-hugo#48]
Dockerfile was already updated for v0.47, but I could not find docker image for v0.47. When will it be released?
https://hub.docker.com/r/jojomi/hugo/tags/

**Comment by hairmare** [comment]
`v0.47` was built into the `latest` tag on docker hub... It looks like `v0.47` needs to be tagged on this repo to get it built into the corresponding tag as well.

**Comment by jojomi** [comment]
Thanks for taking the time to create the issue @superbrothers , I indeed forgot to push the `0.47` tag. Now you should see the docker image tagged as you expected.

**Comment by superbrothers** [comment]
@jojomi @hairmare I was able to find the v0.47 tag. Thank you!
