### ISSUE TITLE
keep ca-certificates

### ISSUE THREAD

**Issue by ssugiyama** [jojomi/docker-hugo#5]
Hi,
https connection is often needed in hugo build process. for example, when using shortcodes. so please don't delete ca-certificates in your Dockerfile.

**Comment by jojomi** [comment]
Thank you for your input!

Can you name an example shortcode depending on having the certificates available at **build time**? I am willing to change the Dockerfile if it makes sense ;-).

**Comment by ssugiyama** [comment]
Among built-in shortcodes (https://gohugo.io/extras/shortcodes/), twitter, youtube, vimeo, and gist are the cases. That is, any shortcodes that fetch data from other sites via https need ca-certificates. (And nowadays most sites support https only).

**Comment by jbleuzen** [comment]
Hi jojomi,
I would use it if I could use twitter shortcode...

You just have to install `ca-certificates`, see [this blog post](http://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/)

**Comment by jojomi** [comment]
Since we by now use `ADD` to put the `tar.gz` archive to the container, I added a new line in the `Dockerfile` installing the `ca-certificates` package. Can one of you verify that this fixes your itch?

**Comment by jbleuzen** [comment]
It's working for me thanks. 👍

**Comment by jojomi** [comment]
Thank you for the feedback @jbleuzen
