### ISSUE TITLE
Hugo should listen to all (0.0.0.0)

### ISSUE THREAD

**Issue by ludovicc** [jojomi/docker-hugo#7]
Hello,

I'm trying to run Hugo in watch mode, but the connection is broken when I navigate to http://localhost:1313. It looks like hugo running inside the container should listen to 0.0.0.0, not 127.0.0.1

I'm using this command:
```
  docker run -i -t --rm -v $(pwd):/src -e HUGO_WATCH=t -p 1313:1313 jojomi/hugo:0.17
```

**Comment by jojomi** [comment]
At first sight that should not be of any difference in the docker container. Did you try and find a fix you can share?

**Comment by ludovicc** [comment]
I searched but could not find an easy solution. If you enter the container with docker exec xxx /bin/sh, install curl and run curl localhost:1313, you get a response. Outside of the container, it's blocked.

**Comment by absolutejam** [comment]
Adding `--bind="0.0.0.0"` to run.sh does the trick - https://github.com/jojomi/docker-hugo/blob/master/run.sh#L16

**Comment by jojomi** [comment]
Thank you for raising this issue @ludovicc and of course thank you for suggesting the fix @absolutejam. I incorporated this and rebuilt the docker images `latest` and `0.17`.
