### ISSUE TITLE
Update for Hugo 0.59.0

### ISSUE THREAD

**Issue by Lucidiot** [jojomi/docker-hugo#80]
A new release is available! https://gohugo.io/news/0.59.0-relnotes/

Can you run your magic update script? :)

**Comment by abeltay** [comment]
https://gohugo.io/news/0.59.1-relnotes/ is out

**Comment by jojomi** [comment]
I just generated the 0.59 and 0.59.1 tags, thank you for the reminder and sorry for the delay and any inconvenience this may have caused.
