### ISSUE TITLE
Update to Hugo v0.60.1

### ISSUE THREAD

**Issue by gavinr** [jojomi/docker-hugo#82]
https://github.com/gohugoio/hugo/releases/tag/v0.60.0

**Comment by abeltay** [comment]
https://github.com/gohugoio/hugo/releases/tag/v0.60.1

**Comment by abcfy2** [comment]
Waiting for this.

**Comment by jojomi** [comment]
Done, thanks for the reminder!

**Comment by gavinr** [comment]
@jojomi thank you!
