### ISSUE TITLE
Execute of template 404 failed

### ISSUE THREAD

**Issue by dimensi0n** [jojomi/docker-hugo#94]
When I run `docker-compose up` I get this error : 

```
Error: Error building site: render of "404" failed: "/src/themes/book/layouts/404.html:26:27": execute of template failed: template: 404.html:26:27: executing "404.html" at <.Site.Home.RelPermalink>: error calling RelPermalink: runtime error: invalid memory address or nil pointer dereference
```
I don't get this when I run `hugo server`

**Comment by jojomi** [comment]
Are you using the same version of the image that `hugo` is reporting locally

**Comment by dimensi0n** [comment]
Yep, it disappear when I add the flag -D, strange behavior

**Comment by dimensi0n** [comment]
I discovered this error comes from the theme I’m using.
